### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by s8321414** [rthomsen/kcmsystemd#11]
Please add localization support,better on Transifex or other online translation platform. :)

**Comment by rthomsen** [comment]
I have just committed localization support along with partial Danish translation. I have no experience with setting up/using Transifex, so help would be appreciated.

**Comment by s8321414** [comment]
Check https://www.transifex.com/pricing/ in "Open source projects" section.
If you can add localization support, I can contribute some zh_TW translations :smile:

**Comment by rthomsen** [comment]
I see kcmsystemd already exists on Transifex:
https://www.transifex.com/projects/p/kcmsystemd/

**Comment by s8321414** [comment]
ah,OK,but is that your official project?

**Comment by rthomsen** [comment]
No, it was created by VictorR2007. I have sent him an email, let's see if he responds...

**Comment by s8321414** [comment]
If he can cooperate with you on this project,it will be a great result!

**Comment by rthomsen** [comment]
VictorR2007 has not responded yet. You can use the Danish or French .po files as template for translation to Taiwanese.

**Comment by s8321414** [comment]
OK,should I fork and translate then send a pull request or just translate and send you .po files?

**Comment by rthomsen** [comment]
It's better if you can send a pull request...

**Comment by s8321414** [comment]
OK,I will do it! Thanks for your quick response! :smile:

**Comment by rthomsen** [comment]
Fixed in 1.1.0

**Comment by s8321414** [comment]
:+1:
