### ISSUE TITLE
not user unit

### ISSUE THREAD

**Issue by papajoker** [rthomsen/kcmsystemd#17]
Hi,
kcmsystemd does not run with user units  ( systemctl --user )

**Comment by rthomsen** [comment]
I have no experience in using user units in systemd. Can you explain in more detail what you mean?

**Comment by papajoker** [comment]
just the same but for one user

    systemctl --user enable notify.timer
    systemctl --user status notify
    systemctl --user list-timers

all files are in ~/config/ and not in /etc/

    ~/.config/systemd/user/timers.target.wants/notify.timer
    ~/.config/systemd/user/notify.timer
    ~/.config/systemd/user/notify.service
    ~/.local/bin/notify.sh

after systemctl --user enable ... , the service is not present in kcmsystemd :(

**Comment by a-detiste** [comment]
Nice guide: https://wiki.archlinux.org/index.php/Systemd/User

**Comment by rthomsen** [comment]
It seems it would be appropriate to add an additional tab with user units. However, there doesn't seem to be a dbus api for the user instance of systemd. Will have to investigate further...

**Comment by a-detiste** [comment]
`dbusviewer`debug tool show me two tabs with `Session bus`and `System bus`

**Comment by a-detiste** [comment]
https://qt.gitorious.org/qt/qttools/source/54027185840ac15b1796903c75cddf15934d9a66:src/qdbus/qdbusviewer/main.cpp#L61-63

`QDBusViewer *sessionBusViewer = new QDBusViewer(QDBusConnection::sessionBus());`

**Comment by rthomsen** [comment]
The session bus does not contain a systemd service on my system...

**Comment by rthomsen** [comment]
Handling of user units has now been implemented. Can you test current master and see if it works correctly on your system?

**Comment by a-detiste** [comment]
I've tested yesterday, it works very nice!

I can't test everything because I have white-on-white tooltips; but that's a bug outside of kcmsystemd. 

Notes:
- to be pedantic, there also exists `user` timers
- it would be a nice to allow filter out from the user tab the units that also exist on the system tab;
to only keep user-exclusive units

**Comment by rthomsen** [comment]
Yes, I'm aware of user timers. I'm thinking about how to best implement that. They could be added to the same QTableView as the system timers or in a separate one... I was thinking it's best to add them to the same to avoid excessive tabs and then create an additional column stating whether it's a system or user timer.

**Comment by a-detiste** [comment]
Yeah, it's best to keep all timers together, maybe some stock icon is enough as a visual clue to diffenrentiate.

**Comment by rthomsen** [comment]
This has now been implemented...
