### ISSUE TITLE
Move to kde-workspaces or extragear

### ISSUE THREAD

**Issue by friesoft** [rthomsen/kcmsystemd#19]
Hi :)

Very nice to see a KDE UI for systemd rising :) 
I guess this would be a candidate to get bundled with kde-workspace as a default package or maybe if the KDE guys don't want to add a hard-dependency on systemd in their workspace it could at least go into extragear.
I guess this would also boost popularity of this kcm module and raise interest in further improving it.

Did you think about talking to the kde devs about this? :)

Keep up the great work :)

Regards,
Bernhard Friedreich

**Comment by rthomsen** [comment]
Thanks for your interest in kcmsystemd. I'm glad you find it useful :+1:

David Edmundson contacted me back in the KDE4 days about that he thought it could be included in extragear. I might try to arrange it when I find the time :)

**Comment by rthomsen** [comment]
kcmsystemd is now up at: http://quickgit.kde.org/?p=systemd-kcm.git

**Comment by friesoft** [comment]
Yeah very nice :) thanks!

**Comment by a-detiste** [comment]
:smile: nice ! ; so how does it work ? development continues here and changes are regularly pulled in kde.org ?

**Comment by rthomsen** [comment]
@a-detiste: I'm not sure. Moving to kde gives us a lot of benefits, such as translations etc. The plan is to eventually have systemd-kcm (as it's called there) released as part of Plasma. When I set up the repository at kde I couldn't figure out how to set-up the commit history, so I started from a clean slate. With my limited git knowledge, I don't know if it's possible to merge changes between the two repositories, but maybe we can keep both in sync. I sure like the GitHub interface...

**Comment by s8321414** [comment]
If this can be plasma 5's official part,it will be good!
You can make this repo a mirror of kde's quickgit :smile:

**Comment by a-detiste** [comment]
by the way, I explicitely agree to relicense my little contributions GPL-2

**Comment by a-detiste** [comment]
> When I set up the repository at kde I couldn't figure out how to set-up the commit history, so I started from a clean slate. 

Well, if you have shell access on this box, you can use `rsync -aivx --delete` to smash this repo it with your private copy.

I'm thinking of other KDE projects needing help, so I may/will request a access anyway (at least to update the french translations before releases)

**Comment by rthomsen** [comment]
> by the way, I explicitely agree to relicense my little contributions GPL-2

Great. Not a license expert, but I think GPL-2 is preferred within KDE.

> I'm thinking of other KDE projects needing help, so I may/will request a access anyway (at least to update the french translations before releases)

Yes, I agree, many KDE projects are rather unmaintained. If you apply for a KDE dev account, I can vouch for you (my kde username: rthomsen) :)

> Well, if you have shell access on this box, you can use rsync -aivx --delete to smash this repo it with your private copy.

Maybe it would make sense to create a new repository on GitHub that mirrors the kde one. Then the name can also be changed to systemd-kcm.

**Comment by a-detiste** [comment]
On https://github.com/rthomsen/kcmsystemd/settings , you can rename the repository ; for the mirroring I don't know how it works (just a cron job with git pull ; git push ?)

**Comment by s8321414** [comment]
My contributions are only translation,don't know if there is any license issue :S

**Comment by s8321414** [comment]
So development will get updated at GitHub or KDE QuickGit now?

**Comment by a-detiste** [comment]
I now found where the translations files have gone :-)

http://websvn.kde.org/trunk/l10n-kf5/fr/messages/playground-sysadmin/systemd-kcm.po

**Comment by rthomsen** [comment]
@s8321414: At the moment on KDE QuickGit. Will try to synchronize a GitHub repository later...

**Comment by s8321414** [comment]
@rthomsen : OK,thanks for your response!
