### ISSUE TITLE
renamed repository on kde git, naming issues for ebuilds

### ISSUE THREAD

**Issue by karolherbst** [rthomsen/kcmsystemd#22]
Because of the different repository name on kde git, we have some issues with naming the ebuilds in gentoo.

The best way to handle it would be to upload renamed tarballs of the last KDE4 and KF5 based versions (0.7.0 and 1.1.0) to the KDE ftp server, so that we can rename the ebuilds fully to systemd-kcm

This request should be rendered null and void, if you intent to keep the name kcmsystemd, but then the upstream kde git repository should be called the same ;)

thank you very much

**Comment by rthomsen** [comment]
Thanks for reporting.

I will upload a renamed tarball for 0.7.0 and 1.1.0 to KDE servers.

**Comment by rthomsen** [comment]
The tarballs should now be up at:
http://download.kde.org/stable/systemd-kcm/

**Comment by karolherbst** [comment]
thank you very much
