### ISSUE TITLE
use other text editor instead kwrite

### ISSUE THREAD

**Issue by sl1pkn07** [rthomsen/kcmsystemd#3]
is possible add option to select default text editor?

greetings

**Comment by s8321414** [comment]
I think it should be a good idea if we can use other text editor :smiley:

**Comment by rthomsen** [comment]
One possibility is to open the unit files using the kde-open5 executable. This will use the editor that is associated with the mime-type, (text/plain for unit files) to open the files.

**Comment by rthomsen** [comment]
13e445ba8a34b4a18c843c010074ebfd0c830811
kcmsystemd now uses the application associated with plain text files for editing unit files. Please test :)
