### ISSUE TITLE
RFE: Journal for units

### ISSUE THREAD

**Issue by penguin42** [rthomsen/kcmsystemd#5]
One nice extension would be to let you get the logs for each unit - perhaps from the right click menu on the unit; i.e. the equivalent of journalctl -u  (possibly allowing you to select only this boot?).

But great work; I've moaned for a while that systemd didn't have the gui tools, and given the number of units in there it can be a pain to find the one you want, so thank you!

**Comment by rthomsen** [comment]
Thank you for the feedback. I'm glad you find kcmsystemd useful. I will think about how this can be implemented...

**Comment by rthomsen** [comment]
The last 5 journal entries for service and scope units are now shown in the tooltip:
980a0d3b4ec6acee144aeddb6106e455abe7ccfb
